export const SET_FORM_DATA = "SET_FORM_DATA";
export const RESET_SIGN_UP_FORM = "RESET_SIGN_UP_FORM";
export const VALIDATION_ERROR = "VALIDATION_ERROR";
export const SET_TEST_USER = "SET_TEST_USER";
export const RESET_FORM = "RESET_FORM";

export const SET_FEED_POSTS = "SET_FEED_POSTS";
export const SET_EXPLORE_POSTS = "SET_EXPLORE_POSTS";
export const SET_ALL_POSTS = "SET_ALL_POSTS";
export const SET_BOOKMARK_POSTS = "SET_BOOKMARK_POST";
export const ADD_TO_BOOKMARK = "ADD_TO_BOOKMARK";
export const SET_CURR_USER_POSTS = "SET_CURR_USER_POSTS";
export const SET_OTHER_USER_POSTS = "SET_OTHER_USER_POSTS";
export const UPDATE_POSTS = "UPDATE_POSTS";

export const SET_USERS = "SET_USERS";
export const SET_SUGGESTED_USER = "SET_SUGGESTED_USER";
export const RESET = "RESET";
export const SET_CURR_USER = "SET_CURR_USER";
export const DELETE_USER_POST = "DELETE_USER_POST";
